[package]
name = "kras"
version = "0.1.0"
authors = ["Nikita Bilous <nikita@bilous.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = '*'
fileinput = "*"
pom = '*'
termcolor = '*'
atty = '*'
log = '*'
env_logger = '*'
chrono = '*'

[dev-dependencies]
rand = '*'

[dependencies.pretty]
features = ['termcolor']
version = '0.10.0'
