indent_style = "Block"
reorder_imports = true
unstable_features = true
control_brace_style = "ClosingNextLine"
# brace_style = "AlwaysNextLine"
struct_field_align_threshold = 20
max_width = 120
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
